### ISSUE TITLE
processing template specific actions (layout module)

### ISSUE THREAD

**Issue by turowski-k** [turowski-k/litesitejs#5]
Requirements:
- [x] Allow for parsing double-brace tags
- [x] Parse partials
- [x] Parse evaluations
- [x] Allow for looping over collections
- [x] Embed stylesheets correctly
- [x] Account for themes

**Comment by turowski-k** [comment]
still needs looping logic

**Comment by turowski-k** [comment]
for correct processing of some of the layouts, this also needs an "if" tag, like this?
`{{?value}}` .. code .. `{{?}}` and a lazy regex on this

**Comment by turowski-k** [comment]
Doing the loop for checking outermost if tags is a horrible job, I have no idea what I am doing wrong at this point

**Comment by turowski-k** [comment]
**Status:** Currently parsing nested brackets works fine, finally.

**Todo:** Need to allow for parsing and running `eval()` on `{{?evaluator}}` brackets, ex `{{?queryParams.q != 'undefined'}}` should run eval on `queryParams.q != 'undefined'` and somehow map the values from viewModel onto the eval.

**Idea:** One way would be (somehow) embedding the eval inside of the viewModel and running it from there? Or we could require the evaluations (all of them, not just ifs) to be prefixed with `vm`, shorthand for viewmodel. Both could work, second if we use `vm` variable for viewmodel as a scoped variable inside the `parseIf` function.

🤔

**Comment by turowski-k** [comment]
this was way easier than I expected it to be
